name: Lens publishing to server

on:
  workflow_call:

env:
  FHIR_SERVER_URL_DEV: https://gravitate-health.lst.tfo.upm.es/epi/api/fhir
  FHIR_SERVER_URL_PROD: https://fosps.gravitatehealth.eu/epi/api/fhir

jobs:
  publish-lens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install -g @gravitate-health/fhir-lens-bundler
      - name: Upload lens
        run: fhir-lens-bundler upload ${{github.event.repository.name}}.json -d ${{ env.FHIR_SERVER_URL_DEV }}
  publish-lens-prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "refs/tags/${{ github.event.inputs.tag }}"
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install -g @gravitate-health/fhir-lens-bundler
      - name: Upload lens
        run: fhir-lens-bundler upload ${{github.event.repository.name}}.json -d ${{ env.FHIR_SERVER_URL_PROD }}
 
