name: Lens publishing to server

on:
  workflow_call:
    secrets:
      DELETE_LENS_URL:
        required: true
      FHIR_SERVER_URL:
        required: true
jobs:
  publish-lens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install -g @gravitate-health/fhir-lens-bundler
      - name: Delete existing lens (if exists)
        run: curl -X DELETE ${{secrets.DELETE_LENS_URL}}${{github.env.repository.name}}
      - name: Upload lens
        run: fhir-lens-bundler upload ${{github.env.repository.name}}.json -d ${{ secrets.FHIR_SERVER_URL }}
